title: "Alan de Guzman"
logo: "img/siteprofileround.png"
description: Data Analyst
- email: &email "aedeguzman@gmail.com"
linkedin: &linkedin "aedeguzman"
show_downloads: false
theme: jekyll-theme-minimal
