  name             : "Alan de Guzman"
  avatar           : "img/siteprofileround.png"
  bio              : "Your biography for the left-hand sidebar"
  location         : "pomona, CA"
show_downloads: false
theme: jekyll-theme-minimal
