name             : "Alan de Guzman"
avatar           : "images/siteprofileround.png"  
bio              : "Data Analyst"
location         : "Pomona, CA"
show_downloads: false
theme: jekyll-theme-minimal
