title: GitHub Pages
title: "Alan de Guzman"
logo: "img/siteprofileround.png"
email: "aedeguzman@gmail.com"
description: >-
  Learn how to create a site or blog from your GitHub repositories with GitHub
  Pages.
show_downloads: false
theme: jekyll-theme-minimal



