  name             : "Your Sidebar Name"
  avatar           : "img/siteprofileround.png"
  location         : "Pomona, CA"
  email            : "aedeguzman@gmail.com
  linkedin         : "aedeguzman"
show_downloads: false
theme: jekyll-theme-minimal
