title: GitHub Pages
title: "Alan de Guzman"
logo: "img/siteprofileround.png"
description: >-
  <em>Data Analyst<em/>
email: "aedeguzman@gmail.com"
show_downloads: false
theme: jekyll-theme-minimal



