title          : "Alan de Guzman"
logo           : "img/siteprofileround.png"
description    : "Data Analyst"
location       : "Pomona, CA"
Email          : "aedeguzman@gmail.com
show_downloads : false
theme          : jekyll-theme-minimal

