title: "Alan de Guzman"
logo: "img/siteprofileround.png"
description: Data Analyst
email: "aedeguzman@gmail.com"
linkedin: "https://www.linkedin.com/in/aedeguzman/"
show_downloads: false
theme: jekyll-theme-minimal
