title: GitHub Pages
title: "Alan de Guzman"
logo: "img/siteprofileround.png"
description: <b>Data Analyst<b/>
url: https://public.tableau.com/app/profile/aedeguzman/vizzes
email: 'aedeguzman@gmail.com'
show_downloads: false
theme: jekyll-theme-minimal



