title: "Alan de Guzman"
logo: "img/siteprofileround.png"
description: "Data Analyst"
"[img align="left" alt="aedeguzman | LinkedIn" width="100px" src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white"/><br/>](https://www.linkedin.com/in/aedeguzman/)"
show_downloads: false
theme: jekyll-theme-minimal

