author:Alan de Guzman
name             : "Alan de Guzman"
avatar           : "images/Linkedinround.png"
bio              : "Data Analyst"
location         : "pomon, CA"
show_downloads: false
theme: jekyll-theme-minimal
